name: Backend CI Pipeline

on:
  push:
    branches:
      - main
      - backend-cache
      - transparencia-v1
      - deploy
  pull_request:
    branches:
      - main
      - backend-cache
      - transparencia-v1
      - deploy
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Instala as dependências
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # Executa os testes do backend
      - name: Run backend tests
        run: |
          cd backend
          npm test
